Section "ServerFlags"
    Option "BlankTime"  "0"
    Option "DontZap"    "false"
EndSection

Section "Device"
    Identifier  "QEMU VGA"
    Driver      "vesa"
    Option      "ShadowFB" "true"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "QEMU VGA"
    DefaultDepth 24
    SubSection "Display"
        Depth    24
        Modes    "1280x720" "1024x768" "800x600"
    EndSubSection
EndSection

Section "InputDevice"
    Identifier "Keyboard0"
    Driver     "kbd"
    Option     "XkbLayout" "us"
EndSection

Section "InputDevice"
    Identifier "Mouse0"
    Driver     "mouse"
    Option     "Protocol"  "ImPS/2"
    Option     "Device"    "/dev/input/mice"
EndSection
