#!/usr/bin/env bash
iso_name="flynnos"
iso_label="FLYNNOS_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
iso_publisher="Flynn OS Project"
iso_application="Flynn OS Linux — The Grid"
iso_version="$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux' 'uefi.systemd-boot')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '15')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
    ["/etc/shadow"]="0:0:400"
    ["/usr/local/bin/flynn-ui"]="0:0:755"
    ["/usr/local/bin/flynn-startx"]="0:0:755"
    ["/usr/local/bin/flynn-draw-bg"]="0:0:755"
    ["/usr/local/bin/flynn-network-init"]="0:0:755"
    ["/usr/local/bin/flynn-wallpaper"]="0:0:755"
    ["/usr/local/bin/flynn-boot-chime"]="0:0:755"
    ["/usr/local/bin/game-mode-switch.sh"]="0:0:755"
    ["/usr/local/bin/flynn-install"]="0:0:755"
    ["/usr/local/bin/proton-ge-install"]="0:0:755"
    ["/usr/local/bin/flynn-compositor-build"]="0:0:755"
    ["/usr/local/bin/flynn-session"]="0:0:755"
    ["/usr/local/bin/flynn-setup"]="0:0:755"
    ["/opt/flynn/daemon/flynn_daemon.py"]="0:0:755"
    ["/opt/flynn/agd/antigravity.py"]="0:0:755"
    ["/root/.xinitrc"]="0:0:755"
    ["/root/.bash_profile"]="0:0:755"
    ["/root/.config/openbox/autostart"]="0:0:755"
    ["/etc/flynn/"]="0:0:755"
    ["/usr/local/bin/flynn-config"]="0:0:755"
    ["/usr/local/bin/flynn-browser"]="0:0:755"
    ["/usr/local/bin/flynn-update"]="0:0:755"
    ["/opt/flynn/notion_anki_sync.py"]="0:0:755"
    ["/opt/flynn/pi-control/pi_agent.py"]="0:0:755"
)
