# Flynn OS Xorg config
# QEMU: uses vesa/vmware driver | AMD: amdgpu auto-detected

Section "ServerFlags"
    Option "BlankTime"   "0"
    Option "DontZap"     "false"
EndSection

Section "InputClass"
    Identifier   "libinput keyboard"
    MatchIsKeyboard "on"
    Driver       "libinput"
    Option       "XkbLayout" "us"
EndSection

Section "InputClass"
    Identifier   "libinput pointer"
    MatchIsPointer "on"
    Driver       "libinput"
    Option       "AccelProfile" "flat"
EndSection
